/**
 * AI Feedback Type Definitions
 * Types for integrating AI-powered feedback with the comment system
 */

import type { TextRange, Reply } from '$lib/comments/types';

/** Supported AI agent names for @mentions */
export type AIAgentName = 'claude' | 'codex' | 'gemini' | 'ai';

/** Status of an AI feedback request */
export type AIFeedbackStatus = 'pending' | 'processing' | 'completed' | 'failed';

/** A suggested text edit from the AI */
export interface SuggestedEdit {
  /** Unique identifier for this edit */
  id: string;
  /** The original text to replace */
  originalText: string;
  /** The suggested replacement text */
  suggestedText: string;
  /** Explanation of why this edit improves the text */
  explanation: string;
  /** Position range in the document */
  range: TextRange;
  /** Whether this edit has been applied */
  applied: boolean;
  /** Whether this edit was rejected by the user */
  rejected: boolean;
}

/** AI metadata attached to a comment */
export interface AIMetadata {
  /** The AI agent being used */
  agentName: AIAgentName;
  /** The user's instruction/question */
  instruction: string;
  /** Current status of the request */
  status: AIFeedbackStatus;
  /** Session ID for follow-up messages */
  sessionId?: string;
  /** Suggested edits from the AI */
  suggestedEdits?: SuggestedEdit[];
  /** Error message if failed */
  error?: string;
}

/** Extended reply type for AI-generated replies */
export interface AIReply extends Reply {
  /** True if this reply was generated by AI */
  aiGenerated: boolean;
  /** AI thinking/reasoning (usually collapsed by default) */
  thinkingContent?: string;
  /** Suggested edits in this reply */
  suggestedEdits?: SuggestedEdit[];
}

/** Request payload for AI feedback */
export interface FeedbackRequest {
  /** Document ID being analyzed */
  documentId: string;
  /** Full document content for context */
  documentContent: string;
  /** Document title */
  documentTitle?: string;
  /** The selected text being commented on */
  selectedText: string;
  /** Position of the selected text */
  selectedRange: TextRange;
  /** User's instruction/question */
  instruction: string;
  /** Executor to use */
  executor: string;
  /** Comment ID to reply to */
  commentId: string;
  /** Session ID for follow-up messages */
  sessionId?: string;
}

/** Response from AI feedback */
export interface FeedbackResponse {
  /** Unique identifier for this feedback */
  id: string;
  /** Current status */
  status: AIFeedbackStatus;
  /** AI response content */
  content?: string;
  /** Suggested edits */
  suggestedEdits: SuggestedEdit[];
  /** Session ID for follow-ups */
  sessionId: string;
  /** Error message if failed */
  error?: string;
}

/** Streaming message from the AI */
export type StreamMessage =
  | { type: 'chunk'; content: string }
  | { type: 'edit'; edit: SuggestedEdit }
  | { type: 'thinking'; content: string }
  | { type: 'complete' }
  | { type: 'error'; message: string };

/** Parsed @mention from comment content */
export interface MentionMatch {
  /** The agent name (claude, codex, gemini, ai) */
  agentName: AIAgentName;
  /** The instruction/question after the @mention */
  instruction: string;
}

/** Regex pattern for detecting @mentions */
export const MENTION_PATTERN = /^@(claude|codex|gemini|ai)\s+(.+)$/i;

/**
 * Detect an @mention in comment content.
 * Returns the parsed mention or null if no match.
 */
export function detectMention(content: string): MentionMatch | null {
  const match = content.trim().match(MENTION_PATTERN);
  if (!match) return null;

  return {
    agentName: match[1].toLowerCase() as AIAgentName,
    instruction: match[2].trim(),
  };
}

/**
 * Check if a reply is AI-generated.
 */
export function isAIReply(reply: Reply | AIReply): reply is AIReply {
  return 'aiGenerated' in reply && reply.aiGenerated === true;
}

/** Available AI agents */
export const AI_AGENTS: Record<AIAgentName, { name: string; description: string }> = {
  claude: {
    name: 'Claude',
    description: 'Anthropic Claude - excellent for writing feedback and analysis',
  },
  codex: {
    name: 'Codex',
    description: 'OpenAI Codex - great for code-related feedback',
  },
  gemini: {
    name: 'Gemini',
    description: 'Google Gemini - versatile AI assistant',
  },
  ai: {
    name: 'AI (Default)',
    description: 'Uses the default configured AI agent',
  },
};
